### ISSUE TITLE
Make attack poses happen on attack

### ISSUE THREAD

**Issue by DaynaLacoursiere** [Panther450/450Game#101]
- [x] Ryker little
- [x] Agni little
- [x] Kitty little
- [x] Delilah little
- [x] Ryker big
- [x] Agni big
- [x] Kitty big
- [x] Delilah big

**Comment by lexiebartlettt** [comment]
I'm not sure if there is a Ryker big? Should he disappear when "Running around" or is how it is good?

**Comment by DaynaLacoursiere** [comment]
Ryker should disappear I think. You could make his semi-transparent self appear in random spots on the map, but I don't think that's necessary. I'll remake the semi-transparent thing with the running sprite.
