### ISSUE TITLE
Fix Sound Warnings

### ISSUE THREAD

**Issue by DaynaLacoursiere** [Panther450/450Game#176]
For the volume menu at the beginning to work, all of the sounds need to be tagged. I set it up so it prints a warning whenever a sound isn't tagged and that's being printed a lot lately.

Please go through all the non-test scenes (and test boss) and tag all the sounds.

**Comment by jjda7a** [comment]
yeah, the reason for that happening is because the sounds are directly attached to the character prefabs which has the tag of "player"
