### ISSUE TITLE
No Excuse Ending Script

### ISSUE THREAD

**Issue by DaynaLacoursiere** [Panther450/450Game#30]
If the players have spared substantially more monsters than they have killed, and rescued the majority of civilians in danger (if these are included in final scope), then the heroes are able to reconcile with Milo and Dr. G. Milo is reconciled with the authorities, and returns to school and the monsters are all collected. Milo threatens to strike again, if he sees monsters still being mistreated.

**Comment by mcmorris** [comment]
Done.  Waiting on feedback!
