### ISSUE TITLE
Player sticks to sides of platforms

### ISSUE THREAD

**Issue by DaynaLacoursiere** [Panther450/450Game#53]

**Comment by mcmorris** [comment]
This issue is caused by usage of only a 2D box collider.  It's fairly well-known.  You can use both a sphere and box collider to resolve it or find other solutions online.

**Comment by DaynaLacoursiere** [comment]
Wow, you're on the ball haha, And ya, I know. Just wanted to add it so it doesn't get forgotten

**Comment by mcmorris** [comment]
What can I say, when it comes to clicking links I'm a pro. XD

Gotcha, good idea.  I've been running into it with testing as well.
