### ISSUE TITLE
Kitty Hiss

### ISSUE THREAD

**Issue by DaynaLacoursiere** [Panther450/450Game#60]
Kitty's hiss should only push enemies in the X-direction

It should also display in one direction (cut off 3/4 of the circle) and should move towards and through the enemies (and scare them when it reaches them). See image linked below

http://bevaudio.com/technical/Dynamic_Cone.gif

**Comment by lexiebartlettt** [comment]
Works fairly well, might need some touch up when final art asset comes in.
